apiVersion: apps/v1
kind: Deployment
metadata:
  name: commsapi-deployment
  labels:
    app: commsapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: commsapi
  template:
    metadata:
      labels:
        app: commsapi
    spec:
      containers:
        - name: commsapi
          image: lichader/communication-api-v1:6
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: commsapi-service
spec:
  selector:
    app: commsapi
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081